"""create tables

Revision ID: 3663655b752a
Revises: 
Create Date: 2023-12-14 21:56:49.426330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3663655b752a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NYC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leading_cause', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('race_ethnicity', sa.String(length=50), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('death_rate', sa.Integer(), nullable=False),
    sa.Column('age_adjusted_death_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nyc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nyc',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leading_cause', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sex', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('race_ethnicity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('deaths', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('death_rate', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_adjusted_death_rate', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('NYC')
    # ### end Alembic commands ###
