# Use Python 3.11 slim image as the base image
FROM python:3.11-slim-buster
# Set the working directory inside the container
WORKDIR /app
# Copy the current directory contents into the container at /app/
COPY . /app/
# Install Python dependencies from requirements.txt
RUN pip install -r requirements.txt
# Expose port 5000
EXPOSE 5000
# Set the default command to run when the container starts
CMD ["python", "app.py"]